# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish aspnetcore-webapp-openidcon-01/aspnetcore-webapp-openidcon-01.csproj
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: website
        path: aspnetcore-webapp-openidcon-01/website/**
        if-no-files-found: error
